[2023-12-10 22:47:58,931] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: pipeline.predict manual__2023-12-10T17:36:27.742952+00:00 [queued]>
[2023-12-10 22:47:58,936] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: pipeline.predict manual__2023-12-10T17:36:27.742952+00:00 [queued]>
[2023-12-10 22:47:58,936] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-12-10 22:47:58,936] {taskinstance.py:1357} INFO - Starting attempt 2 of 6
[2023-12-10 22:47:58,936] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-12-10 22:47:58,949] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): predict> on 2023-12-10 17:36:27.742952+00:00
[2023-12-10 22:47:58,952] {standard_task_runner.py:52} INFO - Started process 26403 to run task
[2023-12-10 22:47:58,954] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline', 'predict', 'manual__2023-12-10T17:36:27.742952+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/final_script.py', '--cfg-path', '/tmp/tmpmk28k3_2', '--error-file', '/tmp/tmp_f4pwjr2']
[2023-12-10 22:47:58,954] {standard_task_runner.py:80} INFO - Job 38: Subtask predict
[2023-12-10 22:47:58,986] {task_command.py:369} INFO - Running <TaskInstance: pipeline.predict manual__2023-12-10T17:36:27.742952+00:00 [running]> on host vmac-VirtualBox
[2023-12-10 22:47:59,028] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Admin
AIRFLOW_CTX_DAG_ID=pipeline
AIRFLOW_CTX_TASK_ID=predict
AIRFLOW_CTX_EXECUTION_DATE=2023-12-10T17:36:27.742952+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-10T17:36:27.742952+00:00
[2023-12-10 22:47:59,029] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-12-10 22:47:59,030] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /home/vmac/lab3/scripts/predict.py']
[2023-12-10 22:47:59,035] {subprocess.py:85} INFO - Output:
[2023-12-10 22:48:00,166] {subprocess.py:92} INFO - [[6264   58]
[2023-12-10 22:48:00,166] {subprocess.py:92} INFO -  [1625   24]] 0.02772963604852686
[2023-12-10 22:48:00,166] {subprocess.py:92} INFO - Traceback (most recent call last):
[2023-12-10 22:48:00,166] {subprocess.py:92} INFO -   File "/home/vmac/lab3/scripts/predict.py", line 21, in <module>
[2023-12-10 22:48:00,166] {subprocess.py:92} INFO -     mlflow.log_metrics('score',float(score))
[2023-12-10 22:48:00,166] {subprocess.py:92} INFO -   File "/home/vmac/lab3/lab3/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 825, in log_metrics
[2023-12-10 22:48:00,166] {subprocess.py:92} INFO -     metrics_arr = [Metric(key, value, timestamp, step or 0) for key, value in metrics.items()]
[2023-12-10 22:48:00,166] {subprocess.py:92} INFO - AttributeError: 'str' object has no attribute 'items'
[2023-12-10 22:48:00,431] {subprocess.py:96} INFO - Command exited with return code 1
[2023-12-10 22:48:00,438] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/vmac/lab3/lab3/lib/python3.10/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-10 22:48:00,442] {taskinstance.py:1395} INFO - Marking task as UP_FOR_RETRY. dag_id=pipeline, task_id=predict, execution_date=20231210T173627, start_date=20231210T174758, end_date=20231210T174800
[2023-12-10 22:48:00,451] {standard_task_runner.py:92} ERROR - Failed to execute job 38 for task predict (Bash command failed. The command returned a non-zero exit code 1.; 26403)
[2023-12-10 22:48:00,473] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-12-10 22:48:00,489] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
