[2023-12-10 22:42:55,719] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: pipeline.predict manual__2023-12-10T17:36:27.742952+00:00 [queued]>
[2023-12-10 22:42:55,723] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: pipeline.predict manual__2023-12-10T17:36:27.742952+00:00 [queued]>
[2023-12-10 22:42:55,723] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-12-10 22:42:55,723] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-12-10 22:42:55,723] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-12-10 22:42:55,738] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): predict> on 2023-12-10 17:36:27.742952+00:00
[2023-12-10 22:42:55,740] {standard_task_runner.py:52} INFO - Started process 26015 to run task
[2023-12-10 22:42:55,742] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline', 'predict', 'manual__2023-12-10T17:36:27.742952+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/final_script.py', '--cfg-path', '/tmp/tmpgli590bk', '--error-file', '/tmp/tmpui4x0bvf']
[2023-12-10 22:42:55,742] {standard_task_runner.py:80} INFO - Job 31: Subtask predict
[2023-12-10 22:42:55,773] {task_command.py:369} INFO - Running <TaskInstance: pipeline.predict manual__2023-12-10T17:36:27.742952+00:00 [running]> on host vmac-VirtualBox
[2023-12-10 22:42:55,812] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Admin
AIRFLOW_CTX_DAG_ID=pipeline
AIRFLOW_CTX_TASK_ID=predict
AIRFLOW_CTX_EXECUTION_DATE=2023-12-10T17:36:27.742952+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-10T17:36:27.742952+00:00
[2023-12-10 22:42:55,815] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-12-10 22:42:55,815] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /home/vmac/lab3/scripts/predict.py']
[2023-12-10 22:42:55,820] {subprocess.py:85} INFO - Output:
[2023-12-10 22:42:57,586] {subprocess.py:92} INFO - [[6264   58]
[2023-12-10 22:42:57,586] {subprocess.py:92} INFO -  [1625   24]] 0.02772963604852686
[2023-12-10 22:42:57,586] {subprocess.py:92} INFO - Traceback (most recent call last):
[2023-12-10 22:42:57,586] {subprocess.py:92} INFO -   File "/home/vmac/lab3/scripts/predict.py", line 21, in <module>
[2023-12-10 22:42:57,586] {subprocess.py:92} INFO -     mlflow.log_metrics('score',float(score))
[2023-12-10 22:42:57,586] {subprocess.py:92} INFO -   File "/home/vmac/lab3/lab3/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 825, in log_metrics
[2023-12-10 22:42:57,586] {subprocess.py:92} INFO -     metrics_arr = [Metric(key, value, timestamp, step or 0) for key, value in metrics.items()]
[2023-12-10 22:42:57,586] {subprocess.py:92} INFO - AttributeError: 'str' object has no attribute 'items'
[2023-12-10 22:42:57,817] {subprocess.py:96} INFO - Command exited with return code 1
[2023-12-10 22:42:57,824] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/vmac/lab3/lab3/lib/python3.10/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-10 22:42:57,826] {taskinstance.py:1395} INFO - Marking task as UP_FOR_RETRY. dag_id=pipeline, task_id=predict, execution_date=20231210T173627, start_date=20231210T174255, end_date=20231210T174257
[2023-12-10 22:42:57,835] {standard_task_runner.py:92} ERROR - Failed to execute job 31 for task predict (Bash command failed. The command returned a non-zero exit code 1.; 26015)
[2023-12-10 22:42:57,857] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-12-10 22:42:57,871] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
